// <auto-generated />
namespace FirstPencilService.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addPoint1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPoint1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505200248548_addPoint1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
