// <auto-generated />
namespace FirstPencilService.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addFirmSimpleName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFirmSimpleName));
        
        string IMigrationMetadata.Id
        {
            get { return "201505250329589_addFirmSimpleName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
